### ISSUE TITLE
Ontology cannot be parsed by OWLAPI due to broken import

### ISSUE THREAD

**Issue by cmungall** [mcourtot/adverse-event-reporting-ontology#2]
```
2017-04-24 16:43:18,762 ERROR (CommandRunner:4348) could not parse:http://purl.obolibrary.org/obo/aero.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/aero/OMRE_AEROImport.owl> Cause: http://ogms.googlecode.com/svn/trunk/src/ontology/omre/OMRE_AEROImport.owl
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1690)
        at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1558)
...
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: http://ogms.googlecode.com/svn/trunk/src/ontology/omre/OMRE_AEROImport.owl
```

So looks like the import is trying to go via OCLC:

```
$ wget http://purl.obolibrary.org/obo/aero/OMRE_AEROImport.owl -O /tmp/z
--2017-04-24 16:46:53--  http://purl.obolibrary.org/obo/aero/OMRE_AEROImport.owl
Resolving purl.obolibrary.org (purl.obolibrary.org)... 52.3.123.63
Connecting to purl.obolibrary.org (purl.obolibrary.org)|52.3.123.63|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://purl.oclc.org/obo/aero/OMRE_AEROImport.owl [following]
--2017-04-24 16:46:53--  http://purl.oclc.org/obo/aero/OMRE_AEROImport.owl
Resolving purl.oclc.org (purl.oclc.org)... 207.241.224.2
Connecting to purl.oclc.org (purl.oclc.org)|207.241.224.2|:80... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://ogms.googlecode.com/svn/trunk/src/ontology/omre/OMRE_AEROImport.owl [following]
--2017-04-24 16:46:54--  http://ogms.googlecode.com/svn/trunk/src/ontology/omre/OMRE_AEROImport.owl
Resolving ogms.googlecode.com (ogms.googlecode.com)... 2607:f8b0:400e:c06::52, 108.177.98.82
Connecting to ogms.googlecode.com (ogms.googlecode.com)|2607:f8b0:400e:c06::52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-24 16:46:54 ERROR 404: Not Found.
```

I could add a purl entry for you, but I can't find the import file in github....

Originally reported here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/410#issuecomment-296842404

**Comment by cmungall** [comment]
@alanruttenberg I see you contribute to this repo any chance you could take care of it while @mcourtot is away?

**Comment by alanruttenberg** [comment]
Looking into it now.

**Comment by alanruttenberg** [comment]
Should be fixed but will test once [pull](https://github.com/OBOFoundry/purl.obolibrary.org/pull/326) gets committed and the purl server updated.

**Comment by mcourtot** [comment]
We should mark this repo as deprecated - I moved AERO to deprecated resources under OBO
